### ISSUE TITLE
images are uncentered in their frames at certain widths

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla-blog#32]
JR notes that photo galleries may not be rendering correctly.

**Comment by JonathanReeve** [comment]
See page 2 of execdirector: 

![selection_522](https://cloud.githubusercontent.com/assets/1843676/6790376/88548108-d17d-11e4-9b04-02c261ab92b9.png)

**Comment by JonathanReeve** [comment]
Fixed in 160e1c3
