### ISSUE TITLE
add link to "no comments" text

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla-blog#37]
Comments are already linked if there are comments. For instance, the text [7 comments] is linked. But if there are no comments, the line reads "No comments," without linking to a place where users can comment. This may effectively discourage users from commenting. 

Since turning "no comments" into a link is semantically bizarre (why would I want to see nothing?), I'd suggest keeping "No comments" unlinked, and adding linked action text that reads "Be the first to leave a comment." Thoughts?

**Comment by JonathanReeve** [comment]
Mockup: 

![selection_010](https://cloud.githubusercontent.com/assets/1843676/7351166/a532d33c-ecd1-11e4-9695-5a4c5b99ace6.jpg)

**Comment by chriszarate** [comment]
Alternative: Users don't need to be informed that there are no comments. Simply provide a link: "Leave a comment."

**Comment by JonathanReeve** [comment]
Let's go with that. That sounds the cleanest.
