### ISSUE TITLE
add link to hypothes.is overlay? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla-blog#38]
Since hypothes.is now has Via, an annotation proxy server, hypothes.is users can highlight and annotate web pages inline, on the level of the word or sentence. I think this is a pretty cool thing, and would allow for basically CommentPress-ifying any page, but on a level even more granular than CommentPress can provide. If we were to provide a link to the via overlay of a blog, e.g. https://via.hypothes.is/http://some-blog.commons.mla.org, we could encourage a wider discussion of blog posts. However, there would be a few caveats: 
 * How would this compete with our current commenting system? I think they could co-exist--hypothes.is for inline comments, and WordPress for post-level comments, but users would still have to get hypothes.is accounts for inline commenting, which might be something we want to avoid implicitly suggesting they do.  
 * Can Via handle pages that have changed? When I tested it on our test server, I get an error complaining that pywb can't proxy the "live web," so I'm guessing that there are a certain number of revisions beyond which pywb considers a page "live." If we were to revise an element on a given page, we might break commenting.  

Instead of providing a link to Via, however, we might be able to use the hypothes.is bookmarklet. I'll do some testing.

**Comment by dwhly** [comment]
> When I tested it on our test server, I get an error complaining that pywb can't proxy the "live web," so I'm guessing that there are a certain number of revisions beyond which pywb considers a page "live." If we were to revise an element on a given page, we might break commenting.

@JonathanReeve Can you show an example of this error?  This doesn't sound like the kind of thing via should break on.  cc @ikreymer

**Comment by JonathanReeve** [comment]
Sure. The pages I was testing were on https://president.thoreau.mlacommons.org. Here's a screenshot of an error: 

![selection_011](https://cloud.githubusercontent.com/assets/1843676/7353842/9b4592c0-ece4-11e4-92bd-79311a19cd05.jpg)

**Comment by dwhly** [comment]
Oh, this may be the same issue as this: https://github.com/hypothesis/via/issues/8#issuecomment-96298946

You can follow the issue above for a notification. cc @judell

**Comment by JonathanReeve** [comment]
Ah. That would be great if it had nothing to do with page mutability, but were an HTTPS issue. I subscribed to the thread--it looks like an easy fix, so that's nice.

**Comment by judell** [comment]
Hey @JonathanReeve , looks like @JonathanReeve  is gone but I'd like to see this happen, can you show me another place were it does?

**Comment by ikreymer** [comment]
A related note: probably makes sense to add more friendly error page for via hypothesis/via#12

**Comment by JonathanReeve** [comment]
@judell, a newer test server is at https://president.dickenson.mlacommons.org. It could be an HTTPS thing, since our test servers might use self-signed certificates. It seems to work on our production site, https://president.commons.mla.org.

**Comment by ikreymer** [comment]
Unfortunately, this seems to be a different error:
```
  File "/Users/ilya/workspace/vpywb/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

Apparently this is an unresolved issue in urllib3 related to openssl:
https://github.com/kennethreitz/requests/issues/2524
https://github.com/shazow/urllib3/issues/556

**Comment by dwhly** [comment]
> A related note: probably makes sense to add more friendly error page for via hypothesis/via#12

@rawkstar77 Can you add this to your design list?  Lets bang out something similar in design to our 404 page.

**Comment by jeremydean** [comment]
how are things going on this one?

**Comment by JonathanReeve** [comment]
I'd like to test out a link to the Via overlay on a dev server, but the above-linked issue (or maybe our SSL-related issues) is still returning a pywb error. I tried the WordPress plugin, but I don't think that would work without a lot of tweaking, since the always-on left panel obscures some buttons in the upper right toolbar.

**Comment by JonathanReeve** [comment]
I think there was also some concern here that the comments wouldn't live on the Commons, and that users would have to log in twice in a session (once to the Commons, and once to hypothes.is). So we might make this one a wishlist item for the moment. But I wonder whether we couldn't install hypothes.is on our own servers for some future open peer review volume like [LSDA](https://dlsanthology.commons.mla.org/).

**Comment by chriszarate** [comment]
Definitely a postpone/wishlist item for us, but potentially a promising one for projects in the pipeline. Closing for now.
