### ISSUE TITLE
clicking on Categories turns page smaller and moves to the left

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla-blog#9]
Here's what it looks like on the FAQ: 

![rights and permissions - frequently asked questions clipular](https://cloud.githubusercontent.com/assets/8835589/4743804/e7c249a6-5a2a-11e4-82d5-ddfe04fc11c8.png)

**Comment by JonathanReeve** [comment]
This early version of the theme has been replaced. Closing.
